import 'styled-components'

declare module 'styled-components' {
    export interface DefaultTheme {
        body: string
        text: string
        textForLogin: string
        primary: string
        background: string
        font: string
        border: string
        label: string
        successBorder: string
        opacity: string
        sidebarBg: string
        sidebarTopBg: string
        sidebarLeftBg: string
        inputBg: string
        inputHeaderBorder: string
        dashboardContentBg: string
        tableHeaderBg: string
        dashboardTitle: string
        inputHeaderInputColor: string
        inputHeaderPlaceholderColor: string
        searchiconSidebar: string
        searchiconSidebarOpacity: string
        notificationColor: string
        notificationBadgeBgColor: string
        breadcrumbColor: string
        breadcrumbSeparatorColor: string
        searchProductsInputBg: string
        searchProductsInputColor: string
        searchProductsPlaceholderColor: string
        searchProductsIconColor: string
        sidebarActiveLinkBg: string
        sidebarLinkColor: string
        sidebarSvgPathColor: string
        languageColor: string
        languageTopColor: string
        languageSvgColor: string
        usernameColor: string
        usernameSvgColor: string
        sidebarToggleBg: string
        sidebarToggleSvgPathColor: string
        prevNextBg: string
        prevNextSvgPathColor: string
        resultsColor: string
        pageNumberInputColor: string
        pageNumberInputBg: string
        iconCtaColor: string
        iconCtaBg: string
        iconCtaBorder: string
        verticalTableOptionsBg: string
        verticalTableOptionsSvgPath: string
        basicButonExpandedBg: string
        pagniationSelectedBg: string
        tableDataRowBg: string
        tableDataRowBrBtmColor: string
        tableBodyTdColor: string
        formTitleColor: string
        forgotPasswordColor: string
        inputBorderColor: string
        inputFieldBg: string
        inputLabelColor: string
        mailIconColor: string
        inputColor: string
        toggleWrapper: string
        sunModeColor: string
        darkModeColor: string
        sunModeBtnBg: string
        darkModeBtnBg: string
        bdContainerBg: string
        bdSingleContentBg: string
        prefilledTitle: string
        prefilledContent: string
        billingDetailsInput: string
        billingDetailsLabel: string
        bdSingleContentTitle: string
        helpText: string
        bdSelectFormColor: string
        modalBg: string
        modalTitle: string
        closeModalSvg: string
        resendLink: string
        langInvoicesBg: string
        langInvoicesLoginscreensBg: string
        langInvoicesTxt: string
        selectEntityLabelBg: string
        selectEntityLabel: string
        selectEntityBorder: string
        selectEntityLabelShrink: string
        selectEntityInput: string
        editableInputBorder: string
        avatarInitialsBg: string
        avatarInitials: string
        datatableIconBg: string
        iconCtaNBg: string
        datatableIconHoverBg: string
        iconCtaTxt: string
        datatableIconHoverTxt: string
        langInvoicesLoginscreensSvg: string
        forgotPasswordLnkColor: string
        cardBorder: string
        cardHoverBorder: string
        verticalDotsBg: string
        verticalDots: string
    }
}
